name: 'Build and Deploy Documentation'
description: 'Builds a documentation website from markdown files and deploys it to GitHub'
inputs:
  input-directory:
    description: 'The directory that contains the markdown files'
    required: true
  css-file:
    description: 'The CSS file to apply to the HTML'
    required: true
runs:
  using: 'node12'
  main: 'index.js'